### ISSUE TITLE
Custom button on back container view becomes disabled after animation

### ISSUE THREAD

**Issue by Jackson0111** [Ramotion/expanding-collection#7]
Great library! I love this thing. But I noticed something very strange, and didn't quite figure out what's going on. I have a button on the back view, but looks like it's disabled when shown after the first animation. Any idea what might cause this? And how it could  be fixed?

**Comment by ctscoville** [comment]
I saw a similar issue, and I think it could be due to the layout of the cells after scrolling or when data gets reloaded.  I saw a problem in the layout where cells were overlapping. Visually everything looks fine, but if you examine the view order, you'll see the cells overlapping and blocking the touch that should get through to the button you want.  I fixed this by making sure the center cell is always on top by adding one line to the layout: https://github.com/ctscoville/expanding-collection/commit/51edd4a28ac055964db4825554ef1a30858525db

You can disregard the whitespace changes in that commit, and you should see the line I added on line 131.

**Comment by vishaladori** [comment]
However, buttons on the back container view arent getting active

**Comment by osmanyildirim** [comment]
@ctscoville  are you sure? Because not working :(

**Comment by iDontCode** [comment]
I have similar issue, and unfortunately @ctscoville's fix does not work. Any other ideas?

**Comment by Mahdimm** [comment]
@ctscoville  hi do you have any open source project I couldnt implement that if there is something please let us know and use it I couldnt understand nothing from usage and demo 
if there is some please help us to know it

**Comment by 0ber** [comment]
it works now 
![tap](https://user-images.githubusercontent.com/5435782/35376109-ab41ff86-01ba-11e8-9bbb-53b81a8ceb57.gif)
